apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  labels:
    argocd.argoproj.io/instance: metallb-configuration-app
  name: pool-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - ip-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  labels:
    argocd.argoproj.io/instance: metallb-configuration-app
  name: ip-pool
  namespace: metallb-system
spec:
  addresses:
    - ${IP_RANGE}