---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "4.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    installCRDs: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-configuration
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: sthings-cluster
      version: 0.2.5
      sourceRef:
        kind: HelmRepository
        name: stuttgart-things
        namespace: flux-system
      interval: 12h
  values:
    installCRDs: true
    customresources:
      addressPool:
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: ip-pool
          namespace: metallb-system
        spec:
          addresses:
          - ${IP_RANGE}
      poolAdvertisement:
        apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: pool-advertisement
          namespace: metallb-system
        spec:
          ipAddressPools:
          - ip-pool
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 20m
  dependsOn:
    - name: metallb
      namespace: metallb-system
  chart:
    spec:
      chart: cert-manager
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 12h
  values:
    installCRDs: true
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: ingress-nginx
#   namespace: ingress-nginx
# spec:
#   interval: 30m
#   dependsOn:
#     - name: metallb
#       namespace: metallb-system
#   chart:
#     spec:
#       chart: ingress-nginx
#       version: "4.x"
#       sourceRef:
#         kind: HelmRepository
#         name: ingress-nginx
#         namespace: flux-system
#       interval: 12h
#   values:
#     installCRDs: true