---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "4.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    installCRDs: true
# ---



      #   chart: sthings-cluster
      # repoURL:
      # targetRevision: 0.2.5


# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   labels:
#     argocd.argoproj.io/instance: metallb-configuration-app
#   name: pool-advertisement
#   namespace: metallb-system
# spec:
#   ipAddressPools:
#     - ip-pool
# ---
# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   labels:
#     argocd.argoproj.io/instance: metallb-configuration-app
#   name: ip-pool
#   namespace: metallb-system
# spec:
#   addresses:
#     - ${IP_RANGE}
# ---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 20m
  chart:
    spec:
      chart: cert-manager
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 12h
  values:
    installCRDs: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  dependsOn:
    - name: metallb
      namespace: metallb-system
  chart:
    spec:
      chart: ingress-nginx
      version: "4.x"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    installCRDs: true