name: linting
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
        
jobs:
  linting:
    continue-on-error: true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Ansible Lint
        uses: ansible/ansible-lint-action@v6.11.0
